/*
 handlebars v2.0.0

 Copyright (C) 2011-2014 by Yehuda Katz

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.

*/
(function(q){var P=window.AmazonUIPageJS||window.P,D=P._namespace||P.attributeErrors,b=D?D("EmberWebsiteHandlebars3PAssets"):P;b.guardFatal?b.guardFatal(q)(b,window):b.execute(function(){q(b,window)})})(function(q,P,D){q.register("ember-handlebars",function(){(function(b,l){"function"===typeof define&&define.amd?define([],l):"object"===typeof exports?module.exports=l():b.Handlebars=b.Handlebars||l()})(this,function(){var b=function(){function b(e){this.string=e}b.prototype.toString=function(){return""+
this.string};return b}(),l=function(b){function e(a){return c[a]}var a={},c={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","`":"&#x60;"},d=/[&<>"'`]/g,h=/[&<>"'`]/;a.extend=function(a){for(var b=1;b<arguments.length;b++)for(var c in arguments[b])Object.prototype.hasOwnProperty.call(arguments[b],c)&&(a[c]=arguments[b][c]);return a};var u=Object.prototype.toString;a.toString=u;var p=function(a){return"function"===typeof a};p(/x/)&&(p=function(a){return"function"===typeof a&&"[object Function]"===
u.call(a)});a.isFunction=p;var w=Array.isArray||function(a){return a&&"object"===typeof a?"[object Array]"===u.call(a):!1};a.isArray=w;a.escapeExpression=function(a){if(a instanceof b)return a.toString();if(null==a)return"";if(!a)return a+"";a=""+a;return h.test(a)?a.replace(d,e):a};a.isEmpty=function(a){return a||0===a?w(a)&&0===a.length?!0:!1:!0};a.appendContextPath=function(a,b){return(a?a+".":"")+b};return a}(b),k=function(){function b(a,c){var d;c&&c.firstLine&&(d=c.firstLine,a+=" - "+d+":"+
c.firstColumn);for(var h=Error.prototype.constructor.call(this,a),u=0;u<e.length;u++)this[e[u]]=h[e[u]];d&&(this.lineNumber=d,this.column=c.firstColumn)}var e="description fileName lineNumber message name number stack".split(" ");b.prototype=Error();return b}(),f=function(b,e){function a(a,b){this.helpers=a||{};this.partials=b||{};c(this)}function c(a){a.registerHelper("helperMissing",function(){if(1===arguments.length)return D;throw new u("Missing helper: '"+arguments[arguments.length-1].name+"'");
});a.registerHelper("blockHelperMissing",function(b,c){var d=c.inverse,u=c.fn;if(!0===b)return u(this);if(!1===b||null==b)return d(this);if(p(b))return 0<b.length?(c.ids&&(c.ids=[c.name]),a.helpers.each(b,c)):d(this);c.data&&c.ids&&(d=l(c.data),d.contextPath=h.appendContextPath(c.data.contextPath,c.name),c={data:d});return u(b,c)});a.registerHelper("each",function(a,b){if(!b)throw new u("Must pass iterator to #each");var c=b.fn,d=b.inverse,e=0,B="",f,g;b.data&&b.ids&&(g=h.appendContextPath(b.data.contextPath,
b.ids[0])+".");w(a)&&(a=a.call(this));b.data&&(f=l(b.data));if(a&&"object"===typeof a)if(p(a))for(var m=a.length;e<m;e++)f&&(f.index=e,f.first=0===e,f.last=e===a.length-1,g&&(f.contextPath=g+e)),B+=c(a[e],{data:f});else for(m in a)a.hasOwnProperty(m)&&(f&&(f.key=m,f.index=e,f.first=0===e,g&&(f.contextPath=g+m)),B+=c(a[m],{data:f}),e++);0===e&&(B=d(this));return B});a.registerHelper("if",function(a,b){w(a)&&(a=a.call(this));return!b.hash.includeZero&&!a||h.isEmpty(a)?b.inverse(this):b.fn(this)});a.registerHelper("unless",
function(b,c){return a.helpers["if"].call(this,b,{fn:c.inverse,inverse:c.fn,hash:c.hash})});a.registerHelper("with",function(a,b){w(a)&&(a=a.call(this));var c=b.fn;if(h.isEmpty(a))return b.inverse(this);if(b.data&&b.ids){var d=l(b.data);d.contextPath=h.appendContextPath(b.data.contextPath,b.ids[0]);b={data:d}}return c(a,b)});a.registerHelper("log",function(b,c){var d=c.data&&null!=c.data.level?parseInt(c.data.level,10):1;a.log(d,b)});a.registerHelper("lookup",function(a,b){return a&&a[b]})}var d=
{},h=b,u=e;d.VERSION="2.0.0";d.COMPILER_REVISION=6;d.REVISION_CHANGES={1:"<= 1.0.rc.2",2:"== 1.0.0-rc.3",3:"== 1.0.0-rc.4",4:"== 1.x.x",5:"== 2.0.0-alpha.x",6:">= 2.0.0-beta.1"};var p=h.isArray,w=h.isFunction,B=h.toString;d.HandlebarsEnvironment=a;a.prototype={constructor:a,logger:f,log:g,registerHelper:function(a,b){if("[object Object]"===B.call(a)){if(b)throw new u("Arg not supported with multiple helpers");h.extend(this.helpers,a)}else this.helpers[a]=b},unregisterHelper:function(a){delete this.helpers[a]},
registerPartial:function(a,b){"[object Object]"===B.call(a)?h.extend(this.partials,a):this.partials[a]=b},unregisterPartial:function(a){delete this.partials[a]}};var f={methodMap:{0:"debug",1:"info",2:"warn",3:"error"},DEBUG:0,INFO:1,WARN:2,ERROR:3,level:3,log:function(a,b){if(f.level<=a){var c=f.methodMap[a];"undefined"!==typeof console&&console[c]&&console[c].call(console,b)}}};d.logger=f;var g=f.log;d.log=g;var l=function(a){var b=h.extend({},a);b._parent=a;return b};d.createFrame=l;return d}(l,
k),g=function(b,e,a){function c(a,b,c,d,h){var p=function(b,p){p=p||{};return c.call(a,b,a.helpers,a.partials,p.data||d,h&&[b].concat(h))};p.program=b;p.depth=h?h.length:0;return p}var d={},h=a.COMPILER_REVISION,u=a.REVISION_CHANGES,p=a.createFrame;d.checkRevision=function(a){var b=a&&a[0]||1;if(b!==h){if(b<h)throw new e("Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version ("+u[h]+") or downgrade your runtime to an older version ("+
u[b]+").");throw new e("Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version ("+a[1]+").");}};d.template=function(a,d){if(!d)throw new e("No environment passed to template");if(!a||!a.main)throw new e("Unknown template object: "+typeof a);d.VM.checkRevision(a.compiler);var h={lookup:function(a,b){for(var c=a.length,d=0;d<c;d++)if(a[d]&&null!=a[d][b])return a[d][b]},lambda:function(a,b){return"function"===typeof a?a.call(b):
a},escapeExpression:b.escapeExpression,invokePartial:function(c,h,p,u,f,g,l,k,n){f&&(u=b.extend({},u,f));f=d.VM.invokePartial.call(this,c,p,u,g,l,k,n);null==f&&d.compile&&(g={helpers:g,partials:l,data:k,depths:n},l[p]=d.compile(c,{data:k!==D,compat:a.compat},d),f=l[p](u,g));if(null!=f){if(h){c=f.split("\n");p=0;for(u=c.length;p<u&&(c[p]||p+1!==u);p++)c[p]=h+c[p];f=c.join("\n")}return f}throw new e("The partial "+p+" could not be compiled when running in runtime-only mode");},fn:function(b){return a[b]},
programs:[],program:function(a,b,d){var h=this.programs[a],p=this.fn(a);b||d?h=c(this,a,p,b,d):h||(h=this.programs[a]=c(this,a,p));return h},data:function(a,b){for(;a&&b--;)a=a._parent;return a},merge:function(a,c){var d=a||c;a&&c&&a!==c&&(d=b.extend({},c,a));return d},noop:d.VM.noop,compilerInfo:a.compiler},u=function(b,c){c=c||{};var d=c.data;u._setup(c);c.partial||!a.useData||d&&"root"in d||(d=d?p(d):{},d.root=b);var e;a.useDepths&&(e=c.depths?[b].concat(c.depths):[b]);return a.main.call(h,b,h.helpers,
h.partials,d,e)};u.isTop=!0;u._setup=function(b){b.partial?(h.helpers=b.helpers,h.partials=b.partials):(h.helpers=h.merge(b.helpers,d.helpers),a.usePartial&&(h.partials=h.merge(b.partials,d.partials)))};u._child=function(b,d,p){if(a.useDepths&&!p)throw new e("must pass parent depths");return c(h,b,a[b],d,p)};return u};d.program=c;d.invokePartial=function(a,b,c,d,h,p,u){d={partial:!0,helpers:d,partials:h,data:p,depths:u};if(a===D)throw new e("The partial "+b+" could not be found");if(a instanceof Function)return a(c,
d)};d.noop=function(){return""};return d}(l,k,f),b=function(b,e,a,c,d){var h=function(){var h=new b.HandlebarsEnvironment;c.extend(h,b);h.SafeString=e;h.Exception=a;h.Utils=c;h.escapeExpression=c.escapeExpression;h.VM=d;h.template=function(a){return d.template(a,h)};return h},u=h();u.create=h;return u["default"]=u}(f,b,k,l,g),g=function(b){function e(a){a=a||{};this.firstLine=a.first_line;this.firstColumn=a.first_column;this.lastColumn=a.last_column;this.lastLine=a.last_line}var a={ProgramNode:function(a,
b,h){e.call(this,h);this.type="program";this.statements=a;this.strip=b},MustacheNode:function(b,d,h,u,p){e.call(this,p);this.type="mustache";this.strip=u;null!=h&&h.charAt?(h=h.charAt(3)||h.charAt(2),this.escaped="{"!==h&&"&"!==h):this.escaped=!!h;this.sexpr=b instanceof a.SexprNode?b:new a.SexprNode(b,d);this.id=this.sexpr.id;this.params=this.sexpr.params;this.hash=this.sexpr.hash;this.eligibleHelper=this.sexpr.eligibleHelper;this.isHelper=this.sexpr.isHelper},SexprNode:function(a,b,h){e.call(this,
h);this.type="sexpr";this.hash=b;h=this.id=a[0];this.eligibleHelper=(this.isHelper=!(!(this.params=a.slice(1)).length&&!b))||h.isSimple},PartialNode:function(a,b,h,u,p){e.call(this,p);this.type="partial";this.partialName=a;this.context=b;this.hash=h;this.strip=u;this.strip.inlineStandalone=!0},BlockNode:function(a,b,h,u,p){e.call(this,p);this.type="block";this.mustache=a;this.program=b;this.inverse=h;this.strip=u;h&&!b&&(this.isInverse=!0)},RawBlockNode:function(c,d,h,u){e.call(this,u);if(c.sexpr.id.original!==
h)throw new b(c.sexpr.id.original+" doesn't match "+h,this);d=new a.ContentNode(d,u);this.type="block";this.mustache=c;this.program=new a.ProgramNode([d],{},u)},ContentNode:function(a,b){e.call(this,b);this.type="content";this.original=this.string=a},HashNode:function(a,b){e.call(this,b);this.type="hash";this.pairs=a},IdNode:function(a,d){e.call(this,d);this.type="ID";for(var h="",u=[],p=0,w="",f=0,g=a.length;f<g;f++){var l=a[f].part,h=h+((a[f].separator||"")+l);if(".."===l||"."===l||"this"===l){if(0<
u.length)throw new b("Invalid path: "+h,this);".."===l?(p++,w+="../"):this.isScoped=!0}else u.push(l)}this.original=h;this.parts=u;this.string=u.join(".");this.depth=p;this.idName=w+this.string;this.isSimple=1===a.length&&!this.isScoped&&0===p;this.stringModeValue=this.string},PartialNameNode:function(a,b){e.call(this,b);this.type="PARTIAL_NAME";this.name=a.original},DataNode:function(a,b){e.call(this,b);this.type="DATA";this.id=a;this.stringModeValue=a.stringModeValue;this.idName="@"+a.stringModeValue},
StringNode:function(a,b){e.call(this,b);this.type="STRING";this.original=this.string=this.stringModeValue=a},NumberNode:function(a,b){e.call(this,b);this.type="NUMBER";this.original=this.number=a;this.stringModeValue=Number(a)},BooleanNode:function(a,b){e.call(this,b);this.type="BOOLEAN";this.bool=a;this.stringModeValue="true"===a},CommentNode:function(a,b){e.call(this,b);this.type="comment";this.comment=a;this.strip={inlineStandalone:!0}}};return a}(k),e=function(){return function(){function b(){this.yy=
{}}var e={trace:function(){},yy:{},symbols_:{error:2,root:3,program:4,EOF:5,program_repetition0:6,statement:7,mustache:8,block:9,rawBlock:10,partial:11,CONTENT:12,COMMENT:13,openRawBlock:14,END_RAW_BLOCK:15,OPEN_RAW_BLOCK:16,sexpr:17,CLOSE_RAW_BLOCK:18,openBlock:19,block_option0:20,closeBlock:21,openInverse:22,block_option1:23,OPEN_BLOCK:24,CLOSE:25,OPEN_INVERSE:26,inverseAndProgram:27,INVERSE:28,OPEN_ENDBLOCK:29,path:30,OPEN:31,OPEN_UNESCAPED:32,CLOSE_UNESCAPED:33,OPEN_PARTIAL:34,partialName:35,
param:36,partial_option0:37,partial_option1:38,sexpr_repetition0:39,sexpr_option0:40,dataName:41,STRING:42,NUMBER:43,BOOLEAN:44,OPEN_SEXPR:45,CLOSE_SEXPR:46,hash:47,hash_repetition_plus0:48,hashSegment:49,ID:50,EQUALS:51,DATA:52,pathSegments:53,SEP:54,$accept:0,$end:1},terminals_:{2:"error",5:"EOF",12:"CONTENT",13:"COMMENT",15:"END_RAW_BLOCK",16:"OPEN_RAW_BLOCK",18:"CLOSE_RAW_BLOCK",24:"OPEN_BLOCK",25:"CLOSE",26:"OPEN_INVERSE",28:"INVERSE",29:"OPEN_ENDBLOCK",31:"OPEN",32:"OPEN_UNESCAPED",33:"CLOSE_UNESCAPED",
34:"OPEN_PARTIAL",42:"STRING",43:"NUMBER",44:"BOOLEAN",45:"OPEN_SEXPR",46:"CLOSE_SEXPR",50:"ID",51:"EQUALS",52:"DATA",54:"SEP"},productions_:[0,[3,2],[4,1],[7,1],[7,1],[7,1],[7,1],[7,1],[7,1],[10,3],[14,3],[9,4],[9,4],[19,3],[22,3],[27,2],[21,3],[8,3],[8,3],[11,5],[11,4],[17,3],[17,1],[36,1],[36,1],[36,1],[36,1],[36,1],[36,3],[47,1],[49,3],[35,1],[35,1],[35,1],[41,2],[30,1],[53,3],[53,1],[6,0],[6,2],[20,0],[20,1],[23,0],[23,1],[37,0],[37,1],[38,0],[38,1],[39,0],[39,2],[40,0],[40,1],[48,1],[48,2]],
performAction:function(a,b,h,u,p,e,f){a=e.length-1;switch(p){case 1:return u.prepareProgram(e[a-1].statements,!0),e[a-1];case 2:this.$=new u.ProgramNode(u.prepareProgram(e[a]),{},this._$);break;case 3:this.$=e[a];break;case 4:this.$=e[a];break;case 5:this.$=e[a];break;case 6:this.$=e[a];break;case 7:this.$=new u.ContentNode(e[a],this._$);break;case 8:this.$=new u.CommentNode(e[a],this._$);break;case 9:this.$=new u.RawBlockNode(e[a-2],e[a-1],e[a],this._$);break;case 10:this.$=new u.MustacheNode(e[a-
1],null,"","",this._$);break;case 11:this.$=u.prepareBlock(e[a-3],e[a-2],e[a-1],e[a],!1,this._$);break;case 12:this.$=u.prepareBlock(e[a-3],e[a-2],e[a-1],e[a],!0,this._$);break;case 13:this.$=new u.MustacheNode(e[a-1],null,e[a-2],u.stripFlags(e[a-2],e[a]),this._$);break;case 14:this.$=new u.MustacheNode(e[a-1],null,e[a-2],u.stripFlags(e[a-2],e[a]),this._$);break;case 15:this.$={strip:u.stripFlags(e[a-1],e[a-1]),program:e[a]};break;case 16:this.$={path:e[a-1],strip:u.stripFlags(e[a-2],e[a])};break;
case 17:this.$=new u.MustacheNode(e[a-1],null,e[a-2],u.stripFlags(e[a-2],e[a]),this._$);break;case 18:this.$=new u.MustacheNode(e[a-1],null,e[a-2],u.stripFlags(e[a-2],e[a]),this._$);break;case 19:this.$=new u.PartialNode(e[a-3],e[a-2],e[a-1],u.stripFlags(e[a-4],e[a]),this._$);break;case 20:this.$=new u.PartialNode(e[a-2],D,e[a-1],u.stripFlags(e[a-3],e[a]),this._$);break;case 21:this.$=new u.SexprNode([e[a-2]].concat(e[a-1]),e[a],this._$);break;case 22:this.$=new u.SexprNode([e[a]],null,this._$);break;
case 23:this.$=e[a];break;case 24:this.$=new u.StringNode(e[a],this._$);break;case 25:this.$=new u.NumberNode(e[a],this._$);break;case 26:this.$=new u.BooleanNode(e[a],this._$);break;case 27:this.$=e[a];break;case 28:e[a-1].isHelper=!0;this.$=e[a-1];break;case 29:this.$=new u.HashNode(e[a],this._$);break;case 30:this.$=[e[a-2],e[a]];break;case 31:this.$=new u.PartialNameNode(e[a],this._$);break;case 32:this.$=new u.PartialNameNode(new u.StringNode(e[a],this._$),this._$);break;case 33:this.$=new u.PartialNameNode(new u.NumberNode(e[a],
this._$));break;case 34:this.$=new u.DataNode(e[a],this._$);break;case 35:this.$=new u.IdNode(e[a],this._$);break;case 36:e[a-2].push({part:e[a],separator:e[a-1]});this.$=e[a-2];break;case 37:this.$=[{part:e[a]}];break;case 38:this.$=[];break;case 39:e[a-1].push(e[a]);break;case 48:this.$=[];break;case 49:e[a-1].push(e[a]);break;case 52:this.$=[e[a]];break;case 53:e[a-1].push(e[a])}},table:[{3:1,4:2,5:[2,38],6:3,12:[2,38],13:[2,38],16:[2,38],24:[2,38],26:[2,38],31:[2,38],32:[2,38],34:[2,38]},{1:[3]},
{5:[1,4]},{5:[2,2],7:5,8:6,9:7,10:8,11:9,12:[1,10],13:[1,11],14:16,16:[1,20],19:14,22:15,24:[1,18],26:[1,19],28:[2,2],29:[2,2],31:[1,12],32:[1,13],34:[1,17]},{1:[2,1]},{5:[2,39],12:[2,39],13:[2,39],16:[2,39],24:[2,39],26:[2,39],28:[2,39],29:[2,39],31:[2,39],32:[2,39],34:[2,39]},{5:[2,3],12:[2,3],13:[2,3],16:[2,3],24:[2,3],26:[2,3],28:[2,3],29:[2,3],31:[2,3],32:[2,3],34:[2,3]},{5:[2,4],12:[2,4],13:[2,4],16:[2,4],24:[2,4],26:[2,4],28:[2,4],29:[2,4],31:[2,4],32:[2,4],34:[2,4]},{5:[2,5],12:[2,5],13:[2,
5],16:[2,5],24:[2,5],26:[2,5],28:[2,5],29:[2,5],31:[2,5],32:[2,5],34:[2,5]},{5:[2,6],12:[2,6],13:[2,6],16:[2,6],24:[2,6],26:[2,6],28:[2,6],29:[2,6],31:[2,6],32:[2,6],34:[2,6]},{5:[2,7],12:[2,7],13:[2,7],16:[2,7],24:[2,7],26:[2,7],28:[2,7],29:[2,7],31:[2,7],32:[2,7],34:[2,7]},{5:[2,8],12:[2,8],13:[2,8],16:[2,8],24:[2,8],26:[2,8],28:[2,8],29:[2,8],31:[2,8],32:[2,8],34:[2,8]},{17:21,30:22,41:23,50:[1,26],52:[1,25],53:24},{17:27,30:22,41:23,50:[1,26],52:[1,25],53:24},{4:28,6:3,12:[2,38],13:[2,38],16:[2,
38],24:[2,38],26:[2,38],28:[2,38],29:[2,38],31:[2,38],32:[2,38],34:[2,38]},{4:29,6:3,12:[2,38],13:[2,38],16:[2,38],24:[2,38],26:[2,38],28:[2,38],29:[2,38],31:[2,38],32:[2,38],34:[2,38]},{12:[1,30]},{30:32,35:31,42:[1,33],43:[1,34],50:[1,26],53:24},{17:35,30:22,41:23,50:[1,26],52:[1,25],53:24},{17:36,30:22,41:23,50:[1,26],52:[1,25],53:24},{17:37,30:22,41:23,50:[1,26],52:[1,25],53:24},{25:[1,38]},{18:[2,48],25:[2,48],33:[2,48],39:39,42:[2,48],43:[2,48],44:[2,48],45:[2,48],46:[2,48],50:[2,48],52:[2,
48]},{18:[2,22],25:[2,22],33:[2,22],46:[2,22]},{18:[2,35],25:[2,35],33:[2,35],42:[2,35],43:[2,35],44:[2,35],45:[2,35],46:[2,35],50:[2,35],52:[2,35],54:[1,40]},{30:41,50:[1,26],53:24},{18:[2,37],25:[2,37],33:[2,37],42:[2,37],43:[2,37],44:[2,37],45:[2,37],46:[2,37],50:[2,37],52:[2,37],54:[2,37]},{33:[1,42]},{20:43,27:44,28:[1,45],29:[2,40]},{23:46,27:47,28:[1,45],29:[2,42]},{15:[1,48]},{25:[2,46],30:51,36:49,38:50,41:55,42:[1,52],43:[1,53],44:[1,54],45:[1,56],47:57,48:58,49:60,50:[1,59],52:[1,25],53:24},
{25:[2,31],42:[2,31],43:[2,31],44:[2,31],45:[2,31],50:[2,31],52:[2,31]},{25:[2,32],42:[2,32],43:[2,32],44:[2,32],45:[2,32],50:[2,32],52:[2,32]},{25:[2,33],42:[2,33],43:[2,33],44:[2,33],45:[2,33],50:[2,33],52:[2,33]},{25:[1,61]},{25:[1,62]},{18:[1,63]},{5:[2,17],12:[2,17],13:[2,17],16:[2,17],24:[2,17],26:[2,17],28:[2,17],29:[2,17],31:[2,17],32:[2,17],34:[2,17]},{18:[2,50],25:[2,50],30:51,33:[2,50],36:65,40:64,41:55,42:[1,52],43:[1,53],44:[1,54],45:[1,56],46:[2,50],47:66,48:58,49:60,50:[1,59],52:[1,
25],53:24},{50:[1,67]},{18:[2,34],25:[2,34],33:[2,34],42:[2,34],43:[2,34],44:[2,34],45:[2,34],46:[2,34],50:[2,34],52:[2,34]},{5:[2,18],12:[2,18],13:[2,18],16:[2,18],24:[2,18],26:[2,18],28:[2,18],29:[2,18],31:[2,18],32:[2,18],34:[2,18]},{21:68,29:[1,69]},{29:[2,41]},{4:70,6:3,12:[2,38],13:[2,38],16:[2,38],24:[2,38],26:[2,38],29:[2,38],31:[2,38],32:[2,38],34:[2,38]},{21:71,29:[1,69]},{29:[2,43]},{5:[2,9],12:[2,9],13:[2,9],16:[2,9],24:[2,9],26:[2,9],28:[2,9],29:[2,9],31:[2,9],32:[2,9],34:[2,9]},{25:[2,
44],37:72,47:73,48:58,49:60,50:[1,74]},{25:[1,75]},{18:[2,23],25:[2,23],33:[2,23],42:[2,23],43:[2,23],44:[2,23],45:[2,23],46:[2,23],50:[2,23],52:[2,23]},{18:[2,24],25:[2,24],33:[2,24],42:[2,24],43:[2,24],44:[2,24],45:[2,24],46:[2,24],50:[2,24],52:[2,24]},{18:[2,25],25:[2,25],33:[2,25],42:[2,25],43:[2,25],44:[2,25],45:[2,25],46:[2,25],50:[2,25],52:[2,25]},{18:[2,26],25:[2,26],33:[2,26],42:[2,26],43:[2,26],44:[2,26],45:[2,26],46:[2,26],50:[2,26],52:[2,26]},{18:[2,27],25:[2,27],33:[2,27],42:[2,27],43:[2,
27],44:[2,27],45:[2,27],46:[2,27],50:[2,27],52:[2,27]},{17:76,30:22,41:23,50:[1,26],52:[1,25],53:24},{25:[2,47]},{18:[2,29],25:[2,29],33:[2,29],46:[2,29],49:77,50:[1,74]},{18:[2,37],25:[2,37],33:[2,37],42:[2,37],43:[2,37],44:[2,37],45:[2,37],46:[2,37],50:[2,37],51:[1,78],52:[2,37],54:[2,37]},{18:[2,52],25:[2,52],33:[2,52],46:[2,52],50:[2,52]},{12:[2,13],13:[2,13],16:[2,13],24:[2,13],26:[2,13],28:[2,13],29:[2,13],31:[2,13],32:[2,13],34:[2,13]},{12:[2,14],13:[2,14],16:[2,14],24:[2,14],26:[2,14],28:[2,
14],29:[2,14],31:[2,14],32:[2,14],34:[2,14]},{12:[2,10]},{18:[2,21],25:[2,21],33:[2,21],46:[2,21]},{18:[2,49],25:[2,49],33:[2,49],42:[2,49],43:[2,49],44:[2,49],45:[2,49],46:[2,49],50:[2,49],52:[2,49]},{18:[2,51],25:[2,51],33:[2,51],46:[2,51]},{18:[2,36],25:[2,36],33:[2,36],42:[2,36],43:[2,36],44:[2,36],45:[2,36],46:[2,36],50:[2,36],52:[2,36],54:[2,36]},{5:[2,11],12:[2,11],13:[2,11],16:[2,11],24:[2,11],26:[2,11],28:[2,11],29:[2,11],31:[2,11],32:[2,11],34:[2,11]},{30:79,50:[1,26],53:24},{29:[2,15]},
{5:[2,12],12:[2,12],13:[2,12],16:[2,12],24:[2,12],26:[2,12],28:[2,12],29:[2,12],31:[2,12],32:[2,12],34:[2,12]},{25:[1,80]},{25:[2,45]},{51:[1,78]},{5:[2,20],12:[2,20],13:[2,20],16:[2,20],24:[2,20],26:[2,20],28:[2,20],29:[2,20],31:[2,20],32:[2,20],34:[2,20]},{46:[1,81]},{18:[2,53],25:[2,53],33:[2,53],46:[2,53],50:[2,53]},{30:51,36:82,41:55,42:[1,52],43:[1,53],44:[1,54],45:[1,56],50:[1,26],52:[1,25],53:24},{25:[1,83]},{5:[2,19],12:[2,19],13:[2,19],16:[2,19],24:[2,19],26:[2,19],28:[2,19],29:[2,19],31:[2,
19],32:[2,19],34:[2,19]},{18:[2,28],25:[2,28],33:[2,28],42:[2,28],43:[2,28],44:[2,28],45:[2,28],46:[2,28],50:[2,28],52:[2,28]},{18:[2,30],25:[2,30],33:[2,30],46:[2,30],50:[2,30]},{5:[2,16],12:[2,16],13:[2,16],16:[2,16],24:[2,16],26:[2,16],28:[2,16],29:[2,16],31:[2,16],32:[2,16],34:[2,16]}],defaultActions:{4:[2,1],44:[2,41],47:[2,43],57:[2,47],63:[2,10],70:[2,15],73:[2,45]},parseError:function(a,b){throw Error(a);},parse:function(a){var b=[0],h=[null],e=[],p=this.table,f="",g=0,m=0,l=0;this.lexer.setInput(a);
this.lexer.yy=this.yy;this.yy.lexer=this.lexer;this.yy.parser=this;"undefined"==typeof this.lexer.yylloc&&(this.lexer.yylloc={});a=this.lexer.yylloc;e.push(a);var k=this.lexer.options&&this.lexer.options.ranges;"function"===typeof this.yy.parseError&&(this.parseError=this.yy.parseError);for(var n,r,E,x,y={},I,L;;){E=b[b.length-1];if(this.defaultActions[E])x=this.defaultActions[E];else{if(null===n||"undefined"==typeof n)n=void 0,n=this.lexer.lex()||1,"number"!==typeof n&&(n=this.symbols_[n]||n);x=
p[E]&&p[E][n]}if("undefined"===typeof x||!x.length||!x[0]){var N="";if(!l){L=[];for(I in p[E])this.terminals_[I]&&2<I&&L.push("'"+this.terminals_[I]+"'");N=this.lexer.showPosition?"Parse error on line "+(g+1)+":\n"+this.lexer.showPosition()+"\nExpecting "+L.join(", ")+", got '"+(this.terminals_[n]||n)+"'":"Parse error on line "+(g+1)+": Unexpected "+(1==n?"end of input":"'"+(this.terminals_[n]||n)+"'");this.parseError(N,{text:this.lexer.match,token:this.terminals_[n]||n,line:this.lexer.yylineno,loc:a,
expected:L})}}if(x[0]instanceof Array&&1<x.length)throw Error("Parse Error: multiple actions possible at state: "+E+", token: "+n);switch(x[0]){case 1:b.push(n);h.push(this.lexer.yytext);e.push(this.lexer.yylloc);b.push(x[1]);n=null;r?(n=r,r=null):(m=this.lexer.yyleng,f=this.lexer.yytext,g=this.lexer.yylineno,a=this.lexer.yylloc,0<l&&l--);break;case 2:L=this.productions_[x[1]][1];y.$=h[h.length-L];y._$={first_line:e[e.length-(L||1)].first_line,last_line:e[e.length-1].last_line,first_column:e[e.length-
(L||1)].first_column,last_column:e[e.length-1].last_column};k&&(y._$.range=[e[e.length-(L||1)].range[0],e[e.length-1].range[1]]);E=this.performAction.call(y,f,m,g,this.yy,x[1],h,e);if("undefined"!==typeof E)return E;L&&(b=b.slice(0,-2*L),h=h.slice(0,-1*L),e=e.slice(0,-1*L));b.push(this.productions_[x[1]][0]);h.push(y.$);e.push(y._$);x=p[b[b.length-2]][b[b.length-1]];b.push(x);break;case 3:return!0}}}},a=function(){return{EOF:1,parseError:function(a,b){if(this.yy.parser)this.yy.parser.parseError(a,
b);else throw Error(a);},setInput:function(a){this._input=a;this._more=this._less=this.done=!1;this.yylineno=this.yyleng=0;this.yytext=this.matched=this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};this.options.ranges&&(this.yylloc.range=[0,0]);this.offset=0;return this},input:function(){var a=this._input[0];this.yytext+=a;this.yyleng++;this.offset++;this.match+=a;this.matched+=a;a.match(/(?:\r\n?|\n).*/g)?(this.yylineno++,this.yylloc.last_line++):
this.yylloc.last_column++;this.options.ranges&&this.yylloc.range[1]++;this._input=this._input.slice(1);return a},unput:function(a){var b=a.length,h=a.split(/(?:\r\n?|\n)/g);this._input=a+this._input;this.yytext=this.yytext.substr(0,this.yytext.length-b-1);this.offset-=b;a=this.match.split(/(?:\r\n?|\n)/g);this.match=this.match.substr(0,this.match.length-1);this.matched=this.matched.substr(0,this.matched.length-1);h.length-1&&(this.yylineno-=h.length-1);var e=this.yylloc.range;this.yylloc={first_line:this.yylloc.first_line,
last_line:this.yylineno+1,first_column:this.yylloc.first_column,last_column:h?(h.length===a.length?this.yylloc.first_column:0)+a[a.length-h.length].length-h[0].length:this.yylloc.first_column-b};this.options.ranges&&(this.yylloc.range=[e[0],e[0]+this.yyleng-b]);return this},more:function(){this._more=!0;return this},less:function(a){this.unput(this.match.slice(a))},pastInput:function(){var a=this.matched.substr(0,this.matched.length-this.match.length);return(20<a.length?"...":"")+a.substr(-20).replace(/\n/g,
"")},upcomingInput:function(){var a=this.match;20>a.length&&(a+=this._input.substr(0,20-a.length));return(a.substr(0,20)+(20<a.length?"...":"")).replace(/\n/g,"")},showPosition:function(){var a=this.pastInput(),b=Array(a.length+1).join("-");return a+this.upcomingInput()+"\n"+b+"^"},next:function(){if(this.done)return this.EOF;this._input||(this.done=!0);var a,b,h;this._more||(this.match=this.yytext="");for(var e=this._currentRules(),p=0;p<e.length&&(!(b=this._input.match(this.rules[e[p]]))||a&&!(b[0].length>
a[0].length)||(a=b,h=p,this.options.flex));p++);if(a){if(b=a[0].match(/(?:\r\n?|\n).*/g))this.yylineno+=b.length;this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+1,first_column:this.yylloc.last_column,last_column:b?b[b.length-1].length-b[b.length-1].match(/\r?\n?/)[0].length:this.yylloc.last_column+a[0].length};this.yytext+=a[0];this.match+=a[0];this.matches=a;this.yyleng=this.yytext.length;this.options.ranges&&(this.yylloc.range=[this.offset,this.offset+=this.yyleng]);this._more=
!1;this._input=this._input.slice(a[0].length);this.matched+=a[0];a=this.performAction.call(this,this.yy,this,e[h],this.conditionStack[this.conditionStack.length-1]);this.done&&this._input&&(this.done=!1);if(a)return a}else return""===this._input?this.EOF:this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var a=this.next();return"undefined"!==typeof a?a:this.lex()},begin:function(a){this.conditionStack.push(a)},
popState:function(){return this.conditionStack.pop()},_currentRules:function(){return this.conditions[this.conditionStack[this.conditionStack.length-1]].rules},topState:function(){return this.conditionStack[this.conditionStack.length-2]},pushState:function(a){this.begin(a)},options:{},performAction:function(a,b,h,e){function p(a,c){return b.yytext=b.yytext.substr(a,b.yyleng-c)}switch(h){case 0:"\\\\"===b.yytext.slice(-2)?(p(0,1),this.begin("mu")):"\\"===b.yytext.slice(-1)?(p(0,1),this.begin("emu")):
this.begin("mu");if(b.yytext)return 12;break;case 1:return 12;case 2:return this.popState(),12;case 3:return b.yytext=b.yytext.substr(5,b.yyleng-9),this.popState(),15;case 4:return 12;case 5:return p(0,4),this.popState(),13;case 6:return 45;case 7:return 46;case 8:return 16;case 9:return this.popState(),this.begin("raw"),18;case 10:return 34;case 11:return 24;case 12:return 29;case 13:return this.popState(),28;case 14:return this.popState(),28;case 15:return 26;case 16:return 26;case 17:return 32;
case 18:return 31;case 19:this.popState();this.begin("com");break;case 20:return p(3,5),this.popState(),13;case 21:return 31;case 22:return 51;case 23:return 50;case 24:return 50;case 25:return 54;case 27:return this.popState(),33;case 28:return this.popState(),25;case 29:return b.yytext=p(1,2).replace(/\\"/g,'"'),42;case 30:return b.yytext=p(1,2).replace(/\\'/g,"'"),42;case 31:return 52;case 32:return 44;case 33:return 44;case 34:return 43;case 35:return 50;case 36:return b.yytext=p(1,2),50;case 37:return"INVALID";
case 38:return 5}},rules:[/^(?:[^\x00]*?(?=(\{\{)))/,/^(?:[^\x00]+)/,/^(?:[^\x00]{2,}?(?=(\{\{|\\\{\{|\\\\\{\{|$)))/,/^(?:\{\{\{\{\/[^\s!"#%-,\.\/;->@\[-\^`\{-~]+(?=[=}\s\/.])\}\}\}\})/,/^(?:[^\x00]*?(?=(\{\{\{\{\/)))/,/^(?:[\s\S]*?--\}\})/,/^(?:\()/,/^(?:\))/,/^(?:\{\{\{\{)/,/^(?:\}\}\}\})/,/^(?:\{\{(~)?>)/,/^(?:\{\{(~)?#)/,/^(?:\{\{(~)?\/)/,/^(?:\{\{(~)?\^\s*(~)?\}\})/,/^(?:\{\{(~)?\s*else\s*(~)?\}\})/,/^(?:\{\{(~)?\^)/,/^(?:\{\{(~)?\s*else\b)/,/^(?:\{\{(~)?\{)/,/^(?:\{\{(~)?&)/,/^(?:\{\{!--)/,
/^(?:\{\{![\s\S]*?\}\})/,/^(?:\{\{(~)?)/,/^(?:=)/,/^(?:\.\.)/,/^(?:\.(?=([=~}\s\/.)])))/,/^(?:[\/.])/,/^(?:\s+)/,/^(?:\}(~)?\}\})/,/^(?:(~)?\}\})/,/^(?:"(\\["]|[^"])*")/,/^(?:'(\\[']|[^'])*')/,/^(?:@)/,/^(?:true(?=([~}\s)])))/,/^(?:false(?=([~}\s)])))/,/^(?:-?[0-9]+(?:\.[0-9]+)?(?=([~}\s)])))/,/^(?:([^\s!"#%-,\.\/;->@\[-\^`\{-~]+(?=([=~}\s\/.)]))))/,/^(?:\[[^\]]*\])/,/^(?:.)/,/^(?:$)/],conditions:{mu:{rules:[6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,
37,38],inclusive:!1},emu:{rules:[2],inclusive:!1},com:{rules:[5],inclusive:!1},raw:{rules:[3,4],inclusive:!1},INITIAL:{rules:[0,1,38],inclusive:!0}}}}();e.lexer=a;b.prototype=e;e.Parser=b;return new b}()}(),n=function(b){function e(a,b,c){b===D&&(b=a.length);var d=a[b-1];a=a[b-2];if(!d)return c;if("content"===d.type)return(a||!c?/\r?\n\s*?$/:/(^|\r?\n)\s*?$/).test(d.original)}function a(a,b,c){b===D&&(b=-1);var d=a[b+1];a=a[b+2];if(!d)return c;if("content"===d.type)return(a||!c?/^\s*?\r?\n/:/^\s*?(\r?\n|$)/).test(d.original)}
function c(a,b,c){!(a=a[null==b?0:b+1])||"content"!==a.type||!c&&a.rightStripped||(b=a.string,a.string=a.string.replace(c?/^\s+/:/^[ \t]*\r?\n?/,""),a.rightStripped=a.string!==b)}function d(a,b,c){if((a=a[null==b?a.length-1:b-1])&&"content"===a.type&&(c||!a.leftStripped))return b=a.string,a.string=a.string.replace(c?/\s+$/:/[ \t]+$/,""),a.leftStripped=a.string!==b,a.leftStripped}return{stripFlags:function(a,b){return{left:"~"===a.charAt(2),right:"~"===b.charAt(b.length-3)}},prepareBlock:function(h,
u,p,f,g,l){if(h.sexpr.id.original!==f.path.original)throw new b(h.sexpr.id.original+" doesn't match "+f.path.original,h);var k=p&&p.program,n={left:h.strip.left,right:f.strip.right,openStandalone:a(u.statements),closeStandalone:e((k||u).statements)};h.strip.right&&c(u.statements,null,!0);k?(p=p.strip,p.left&&d(u.statements,null,!0),p.right&&c(k.statements,null,!0),f.strip.left&&d(k.statements,null,!0),e(u.statements)&&a(k.statements)&&(d(u.statements),c(k.statements))):f.strip.left&&d(u.statements,
null,!0);return g?new this.BlockNode(h,k,u,n,l):new this.BlockNode(h,u,k,n,l)},prepareProgram:function(b,u){for(var p=0,f=b.length;p<f;p++){var g=b[p],m=g.strip;if(m){var l=e(b,p,u,"partial"===g.type),k=a(b,p,u),n=m.openStandalone&&l,v=m.closeStandalone&&k,l=m.inlineStandalone&&l&&k;m.right&&c(b,p,!0);m.left&&d(b,p,!0);l&&(c(b,p),d(b,p)&&"partial"===g.type&&(g.indent=/([ \t]+$)/.exec(b[p-1].original)?RegExp.$1:""));n&&(c((g.program||g.inverse).statements),d(b,p));v&&(c(b,p),d((g.inverse||g.program).statements))}}return b}}}(k),
e=function(b,e,a,c){var d={};c=c.extend;d.parser=b;var h={};c(h,a,e);d.parse=function(a){if(a.constructor===e.ProgramNode)return a;b.yy=h;return b.parse(a)};return d}(e,g,n,l),l=function(b,e){function a(){}function c(a,b){if(a===b)return!0;if(h(a)&&h(b)&&a.length===b.length){for(var d=0;d<a.length;d++)if(!c(a[d],b[d]))return!1;return!0}}var d={},h=e.isArray,u=[].slice;d.Compiler=a;a.prototype={compiler:a,equals:function(a){var b=this.opcodes.length;if(a.opcodes.length!==b)return!1;for(var d=0;d<b;d++){var h=
this.opcodes[d],e=a.opcodes[d];if(h.opcode!==e.opcode||!c(h.args,e.args))return!1}b=this.children.length;for(d=0;d<b;d++)if(!this.children[d].equals(a.children[d]))return!1;return!0},guid:0,compile:function(a,b){this.opcodes=[];this.children=[];this.depths={list:[]};this.options=b;this.stringParams=b.stringParams;this.trackIds=b.trackIds;var c=this.options.knownHelpers;this.options.knownHelpers={helperMissing:!0,blockHelperMissing:!0,each:!0,"if":!0,unless:!0,"with":!0,log:!0,lookup:!0};if(c)for(var d in c)this.options.knownHelpers[d]=
c[d];return this.accept(a)},accept:function(a){return this[a.type](a)},program:function(a){a=a.statements;for(var b=0,c=a.length;b<c;b++)this.accept(a[b]);this.isSimple=1===c;this.depths.list=this.depths.list.sort(function(a,b){return a-b});return this},compileProgram:function(a){a=(new this.compiler).compile(a,this.options);var b=this.guid++,c;this.usePartial=this.usePartial||a.usePartial;this.children[b]=a;for(var d=0,h=a.depths.list.length;d<h;d++)c=a.depths.list[d],2>c||this.addDepth(c-1);return b},
block:function(a){var b=a.mustache,c=a.program;a=a.inverse;c&&(c=this.compileProgram(c));a&&(a=this.compileProgram(a));var b=b.sexpr,d=this.classifySexpr(b);"helper"===d?this.helperSexpr(b,c,a):"simple"===d?(this.simpleSexpr(b),this.opcode("pushProgram",c),this.opcode("pushProgram",a),this.opcode("emptyHash"),this.opcode("blockValue",b.id.original)):(this.ambiguousSexpr(b,c,a),this.opcode("pushProgram",c),this.opcode("pushProgram",a),this.opcode("emptyHash"),this.opcode("ambiguousBlockValue"));this.opcode("append")},
hash:function(a){a=a.pairs;var b,c;this.opcode("pushHash");b=0;for(c=a.length;b<c;b++)this.pushParam(a[b][1]);for(;b--;)this.opcode("assignToHash",a[b][0]);this.opcode("popHash")},partial:function(a){var b=a.partialName;this.usePartial=!0;a.hash?this.accept(a.hash):this.opcode("push","undefined");a.context?this.accept(a.context):(this.opcode("getContext",0),this.opcode("pushContext"));this.opcode("invokePartial",b.name,a.indent||"");this.opcode("append")},content:function(a){a.string&&this.opcode("appendContent",
a.string)},mustache:function(a){this.sexpr(a.sexpr);a.escaped&&!this.options.noEscape?this.opcode("appendEscaped"):this.opcode("append")},ambiguousSexpr:function(a,b,c){a=a.id;var d=a.parts[0],h=null!=b||null!=c;this.opcode("getContext",a.depth);this.opcode("pushProgram",b);this.opcode("pushProgram",c);this.ID(a);this.opcode("invokeAmbiguous",d,h)},simpleSexpr:function(a){a=a.id;"DATA"===a.type?this.DATA(a):a.parts.length?this.ID(a):(this.addDepth(a.depth),this.opcode("getContext",a.depth),this.opcode("pushContext"));
this.opcode("resolvePossibleLambda")},helperSexpr:function(a,c,d){c=this.setupFullMustacheParams(a,c,d);d=a.id;var h=d.parts[0];if(this.options.knownHelpers[h])this.opcode("invokeKnownHelper",c.length,h);else{if(this.options.knownHelpersOnly)throw new b("You specified knownHelpersOnly, but used the unknown helper "+h,a);d.falsy=!0;this.ID(d);this.opcode("invokeHelper",c.length,d.original,d.isSimple)}},sexpr:function(a){var b=this.classifySexpr(a);"simple"===b?this.simpleSexpr(a):"helper"===b?this.helperSexpr(a):
this.ambiguousSexpr(a)},ID:function(a){this.addDepth(a.depth);this.opcode("getContext",a.depth);a.parts[0]?this.opcode("lookupOnContext",a.parts,a.falsy,a.isScoped):this.opcode("pushContext")},DATA:function(a){this.options.data=!0;this.opcode("lookupData",a.id.depth,a.id.parts)},STRING:function(a){this.opcode("pushString",a.string)},NUMBER:function(a){this.opcode("pushLiteral",a.number)},BOOLEAN:function(a){this.opcode("pushLiteral",a.bool)},comment:function(){},opcode:function(a){this.opcodes.push({opcode:a,
args:u.call(arguments,1)})},addDepth:function(a){0===a||this.depths[a]||(this.depths[a]=!0,this.depths.list.push(a))},classifySexpr:function(a){var b=a.isHelper,c=a.eligibleHelper,d=this.options;c&&!b&&(d.knownHelpers[a.id.parts[0]]?b=!0:d.knownHelpersOnly&&(c=!1));return b?"helper":c?"ambiguous":"simple"},pushParams:function(a){for(var b=0,c=a.length;b<c;b++)this.pushParam(a[b])},pushParam:function(a){this.stringParams?(a.depth&&this.addDepth(a.depth),this.opcode("getContext",a.depth||0),this.opcode("pushStringParam",
a.stringModeValue,a.type),"sexpr"===a.type&&this.sexpr(a)):(this.trackIds&&this.opcode("pushId",a.type,a.idName||a.stringModeValue),this.accept(a))},setupFullMustacheParams:function(a,b,c){var d=a.params;this.pushParams(d);this.opcode("pushProgram",b);this.opcode("pushProgram",c);a.hash?this.hash(a.hash):this.opcode("emptyHash");return d}};d.precompile=function(a,c,d){if(null==a||"string"!==typeof a&&a.constructor!==d.AST.ProgramNode)throw new b("You must pass a string or Handlebars AST to Handlebars.precompile. You passed "+
a);c=c||{};"data"in c||(c.data=!0);c.compat&&(c.useDepths=!0);a=d.parse(a);a=(new d.Compiler).compile(a,c);return(new d.JavaScriptCompiler).compile(a,c)};d.compile=function(a,c,d){function h(){var b=d.parse(a),b=(new d.Compiler).compile(b,c),b=(new d.JavaScriptCompiler).compile(b,c,D,!0);return d.template(b)}if(null==a||"string"!==typeof a&&a.constructor!==d.AST.ProgramNode)throw new b("You must pass a string or Handlebars AST to Handlebars.compile. You passed "+a);c=c||{};"data"in c||(c.data=!0);
c.compat&&(c.useDepths=!0);var e,u=function(a,b){e||(e=h());return e.call(this,a,b)};u._setup=function(a){e||(e=h());return e._setup(a)};u._child=function(a,b,c){e||(e=h());return e._child(a,b,c)};return u};return d}(k,l),k=function(b,e){function a(a){this.value=a}function c(){}var d=b.COMPILER_REVISION,h=b.REVISION_CHANGES;c.prototype={nameLookup:function(a,b){return c.isValidJavaScriptVariableName(b)?a+"."+b:a+"['"+b+"']"},depthedLookup:function(a){this.aliases.lookup="this.lookup";return'lookup(depths, "'+
a+'")'},compilerInfo:function(){return[d,h[d]]},appendToBuffer:function(a){return this.environment.isSimple?"return "+a+";":{appendToBuffer:!0,content:a,toString:function(){return"buffer += "+a+";"}}},initializeBuffer:function(){return this.quotedString("")},namespace:"Handlebars",compile:function(a,b,c,d){this.environment=a;this.options=b;this.stringParams=this.options.stringParams;this.trackIds=this.options.trackIds;this.precompile=!d;this.name=this.environment.name;this.isChild=!!c;this.context=
c||{programs:[],environments:[]};this.preamble();this.stackSlot=0;this.stackVars=[];this.aliases={};this.registers={list:[]};this.hashes=[];this.compileStack=[];this.inlineStack=[];this.compileChildren(a,b);this.useDepths=this.useDepths||a.depths.list.length||this.options.compat;c=a.opcodes;var h;a=0;for(b=c.length;a<b;a++)h=c[a],this[h.opcode].apply(this,h.args);this.pushSource("");if(this.stackSlot||this.inlineStack.length||this.compileStack.length)throw new e("Compile completed with content left on stack");
a=this.createFunctionContext(d);if(this.isChild)return a;c={compiler:this.compilerInfo(),main:a};h=this.context.programs;a=0;for(b=h.length;a<b;a++)h[a]&&(c[a]=h[a]);this.environment.usePartial&&(c.usePartial=!0);this.options.data&&(c.useData=!0);this.useDepths&&(c.useDepths=!0);this.options.compat&&(c.compat=!0);d||(c.compiler=JSON.stringify(c.compiler),c=this.objectLiteral(c));return c},preamble:function(){this.lastContext=0;this.source=[]},createFunctionContext:function(a){var b="",c=this.stackVars.concat(this.registers.list);
0<c.length&&(b+=", "+c.join(", "));for(var d in this.aliases)this.aliases.hasOwnProperty(d)&&(b+=", "+d+"="+this.aliases[d]);c=["depth0","helpers","partials","data"];this.useDepths&&c.push("depths");b=this.mergeSource(b);return a?(c.push(b),Function.apply(this,c)):"function("+c.join(",")+") {\n  "+b+"}"},mergeSource:function(a){for(var b="",c,d=!this.forceBuffer,h,e=0,u=this.source.length;e<u;e++){var p=this.source[e];p.appendToBuffer?c=c?c+"\n    + "+p.content:p.content:(c&&(b?b+="buffer += "+c+
";\n  ":(h=!0,b=c+";\n  "),c=D),b+=p+"\n  ",this.environment.isSimple||(d=!1))}if(d){if(c||!b)b+="return "+(c||'""')+";\n"}else a+=", buffer = "+(h?"":this.initializeBuffer()),b=c?b+("return buffer + "+c+";\n"):b+"return buffer;\n";a&&(b="var "+a.substring(2)+(h?"":";\n  ")+b);return b},blockValue:function(a){this.aliases.blockHelperMissing="helpers.blockHelperMissing";var b=[this.contextName(0)];this.setupParams(a,0,b);a=this.popStack();b.splice(1,0,a);this.push("blockHelperMissing.call("+b.join(", ")+
")")},ambiguousBlockValue:function(){this.aliases.blockHelperMissing="helpers.blockHelperMissing";var a=[this.contextName(0)];this.setupParams("",0,a,!0);this.flushInline();var b=this.topStack();a.splice(1,0,b);this.pushSource("if (!"+this.lastHelper+") { "+b+" = blockHelperMissing.call("+a.join(", ")+"); }")},appendContent:function(a){this.pendingContent&&(a=this.pendingContent+a);this.pendingContent=a},append:function(){this.flushInline();var a=this.popStack();this.pushSource("if ("+a+" != null) { "+
this.appendToBuffer(a)+" }");this.environment.isSimple&&this.pushSource("else { "+this.appendToBuffer("''")+" }")},appendEscaped:function(){this.aliases.escapeExpression="this.escapeExpression";this.pushSource(this.appendToBuffer("escapeExpression("+this.popStack()+")"))},getContext:function(a){this.lastContext=a},pushContext:function(){this.pushStackLiteral(this.contextName(this.lastContext))},lookupOnContext:function(a,b,c){var d=0,h=a.length;for(c||!this.options.compat||this.lastContext?this.pushContext():
this.push(this.depthedLookup(a[d++]));d<h;d++)this.replaceStack(function(c){var h=this.nameLookup(c,a[d],"context");return b?" && "+h:" != null ? "+h+" : "+c})},lookupData:function(a,b){a?this.pushStackLiteral("this.data(data, "+a+")"):this.pushStackLiteral("data");for(var c=b.length,d=0;d<c;d++)this.replaceStack(function(a){return" && "+this.nameLookup(a,b[d],"data")})},resolvePossibleLambda:function(){this.aliases.lambda="this.lambda";this.push("lambda("+this.popStack()+", "+this.contextName(0)+
")")},pushStringParam:function(a,b){this.pushContext();this.pushString(b);"sexpr"!==b&&("string"===typeof a?this.pushString(a):this.pushStackLiteral(a))},emptyHash:function(){this.pushStackLiteral("{}");this.trackIds&&this.push("{}");this.stringParams&&(this.push("{}"),this.push("{}"))},pushHash:function(){this.hash&&this.hashes.push(this.hash);this.hash={values:[],types:[],contexts:[],ids:[]}},popHash:function(){var a=this.hash;this.hash=this.hashes.pop();this.trackIds&&this.push("{"+a.ids.join(",")+
"}");this.stringParams&&(this.push("{"+a.contexts.join(",")+"}"),this.push("{"+a.types.join(",")+"}"));this.push("{\n    "+a.values.join(",\n    ")+"\n  }")},pushString:function(a){this.pushStackLiteral(this.quotedString(a))},push:function(a){this.inlineStack.push(a);return a},pushLiteral:function(a){this.pushStackLiteral(a)},pushProgram:function(a){null!=a?this.pushStackLiteral(this.programExpression(a)):this.pushStackLiteral(null)},invokeHelper:function(a,b,c){this.aliases.helperMissing="helpers.helperMissing";
var d=this.popStack();a=this.setupHelper(a,b);this.push("(("+((c?a.name+" || ":"")+d+" || helperMissing")+").call("+a.callParams+"))")},invokeKnownHelper:function(a,b){var c=this.setupHelper(a,b);this.push(c.name+".call("+c.callParams+")")},invokeAmbiguous:function(a,b){this.aliases.functionType='"function"';this.aliases.helperMissing="helpers.helperMissing";this.useRegister("helper");var c=this.popStack();this.emptyHash();var d=this.setupHelper(0,a,b),h=this.lastHelper=this.nameLookup("helpers",
a,"helper");this.push("((helper = (helper = "+h+" || "+c+") != null ? helper : helperMissing"+(d.paramsInit?"),("+d.paramsInit:"")+"),(typeof helper === functionType ? helper.call("+d.callParams+") : helper))")},invokePartial:function(a,b){var c=[this.nameLookup("partials",a,"partial"),"'"+b+"'","'"+a+"'",this.popStack(),this.popStack(),"helpers","partials"];this.options.data?c.push("data"):this.options.compat&&c.push("undefined");this.options.compat&&c.push("depths");this.push("this.invokePartial("+
c.join(", ")+")")},assignToHash:function(a){var b=this.popStack(),c,d,h;this.trackIds&&(h=this.popStack());this.stringParams&&(d=this.popStack(),c=this.popStack());var e=this.hash;c&&e.contexts.push("'"+a+"': "+c);d&&e.types.push("'"+a+"': "+d);h&&e.ids.push("'"+a+"': "+h);e.values.push("'"+a+"': ("+b+")")},pushId:function(a,b){"ID"===a||"DATA"===a?this.pushString(b):"sexpr"===a?this.pushStackLiteral("true"):this.pushStackLiteral("null")},compiler:c,compileChildren:function(a,b){for(var c=a.children,
d,h,e=0,u=c.length;e<u;e++){d=c[e];h=new this.compiler;var p=this.matchExistingProgram(d);null==p?(this.context.programs.push(""),p=this.context.programs.length,d.index=p,d.name="program"+p,this.context.programs[p]=h.compile(d,b,this.context,!this.precompile),this.context.environments[p]=d,this.useDepths=this.useDepths||h.useDepths):(d.index=p,d.name="program"+p)}},matchExistingProgram:function(a){for(var b=0,c=this.context.environments.length;b<c;b++){var d=this.context.environments[b];if(d&&d.equals(a))return b}},
programExpression:function(a){a=[this.environment.children[a].index,"data"];this.useDepths&&a.push("depths");return"this.program("+a.join(", ")+")"},useRegister:function(a){this.registers[a]||(this.registers[a]=!0,this.registers.list.push(a))},pushStackLiteral:function(b){return this.push(new a(b))},pushSource:function(a){this.pendingContent&&(this.source.push(this.appendToBuffer(this.quotedString(this.pendingContent))),this.pendingContent=D);a&&this.source.push(a)},pushStack:function(a){this.flushInline();
var b=this.incrStack();this.pushSource(b+" = "+a+";");this.compileStack.push(b);return b},replaceStack:function(b){var c="";this.isInline();var d,h,u;if(!this.isInline())throw new e("replaceStack on non-inline");c=this.popStack(!0);c instanceof a?(c=d=c.value,u=!0):(d=(h=!this.stackSlot)?this.incrStack():this.topStackName(),c="("+this.push(d)+" = "+c+")",d=this.topStack());b=b.call(this,d);u||this.popStack();h&&this.stackSlot--;this.push("("+c+b+")")},incrStack:function(){this.stackSlot++;this.stackSlot>
this.stackVars.length&&this.stackVars.push("stack"+this.stackSlot);return this.topStackName()},topStackName:function(){return"stack"+this.stackSlot},flushInline:function(){var b=this.inlineStack;if(b.length){this.inlineStack=[];for(var c=0,d=b.length;c<d;c++){var h=b[c];h instanceof a?this.compileStack.push(h):this.pushStack(h)}}},isInline:function(){return this.inlineStack.length},popStack:function(b){var c=this.isInline(),d=(c?this.inlineStack:this.compileStack).pop();if(!b&&d instanceof a)return d.value;
if(!c){if(!this.stackSlot)throw new e("Invalid stack pop");this.stackSlot--}return d},topStack:function(){var b=this.isInline()?this.inlineStack:this.compileStack,b=b[b.length-1];return b instanceof a?b.value:b},contextName:function(a){return this.useDepths&&a?"depths["+a+"]":"depth"+a},quotedString:function(a){return'"'+a.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\u2028/g,"\\u2028").replace(/\u2029/g,"\\u2029")+'"'},objectLiteral:function(a){var b=
[],c;for(c in a)a.hasOwnProperty(c)&&b.push(this.quotedString(c)+":"+a[c]);return"{"+b.join(",")+"}"},setupHelper:function(a,b,c){var d=[];a=this.setupParams(b,a,d,c);b=this.nameLookup("helpers",b,"helper");return{params:d,paramsInit:a,name:b,callParams:[this.contextName(0)].concat(d).join(", ")}},setupOptions:function(a,b,c){var d={},h=[],e=[],u=[],p;d.name=this.quotedString(a);d.hash=this.popStack();this.trackIds&&(d.hashIds=this.popStack());this.stringParams&&(d.hashTypes=this.popStack(),d.hashContexts=
this.popStack());a=this.popStack();if((p=this.popStack())||a)p||(p="this.noop"),a||(a="this.noop"),d.fn=p,d.inverse=a;for(a=b;a--;)b=this.popStack(),c[a]=b,this.trackIds&&(u[a]=this.popStack()),this.stringParams&&(e[a]=this.popStack(),h[a]=this.popStack());this.trackIds&&(d.ids="["+u.join(",")+"]");this.stringParams&&(d.types="["+e.join(",")+"]",d.contexts="["+h.join(",")+"]");this.options.data&&(d.data="data");return d},setupParams:function(a,b,c,d){a=this.objectLiteral(this.setupOptions(a,b,c));
if(d)return this.useRegister("options"),c.push("options"),"options="+a;c.push(a);return""}};for(var u="break else new var case finally return void catch for switch while continue function this with default if throw delete in try do instanceof typeof abstract enum int short boolean export interface static byte extends long super char final native synchronized class float package throws const goto private transient debugger implements protected volatile double import public let yield".split(" "),p=
c.RESERVED_WORDS={},f=0,g=u.length;f<g;f++)p[u[f]]=!0;c.isValidJavaScriptVariableName=function(a){return!c.RESERVED_WORDS[a]&&/^[a-zA-Z_$][0-9a-zA-Z_$]*$/.test(a)};return c}(f,k);return function(b,e,a,c,d){var h=a.parser,u=a.parse,p=c.Compiler,f=c.compile,g=c.precompile,l=b.create;a=function(){var a=l();a.compile=function(b,c){return f(b,c,a)};a.precompile=function(b,c){return g(b,c,a)};a.AST=e;a.Compiler=p;a.JavaScriptCompiler=d;a.Parser=h;a.parse=u;return a};b=a();b.create=a;return b["default"]=
b}(b,g,e,l,k)});return{Handlebars:P.Handlebars}})});